# CMake generated Testfile for 
# Source directory: /mnt/d/OneDrive - Office/File/Project/VS Code/C++/xianyi-OpenBLAS-efe4248/test
# Build directory: /mnt/d/OneDrive - Office/File/Project/VS Code/C++/xianyi-OpenBLAS-efe4248/test
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(sblas1 "/mnt/d/OneDrive - Office/File/Project/VS Code/C++/xianyi-OpenBLAS-efe4248/test/sblat1")
set_tests_properties(sblas1 PROPERTIES  _BACKTRACE_TRIPLES "/mnt/d/OneDrive - Office/File/Project/VS Code/C++/xianyi-OpenBLAS-efe4248/test/CMakeLists.txt;72;add_test;/mnt/d/OneDrive - Office/File/Project/VS Code/C++/xianyi-OpenBLAS-efe4248/test/CMakeLists.txt;0;")
add_test(sblas2 "sh" "/mnt/d/OneDrive - Office/File/Project/VS Code/C++/xianyi-OpenBLAS-efe4248/test/test_helper.sh" "/mnt/d/OneDrive - Office/File/Project/VS Code/C++/xianyi-OpenBLAS-efe4248/test/sblat2" "/mnt/d/OneDrive - Office/File/Project/VS Code/C++/xianyi-OpenBLAS-efe4248/test/sblat2.dat" "SBLAT2.SUMM")
set_tests_properties(sblas2 PROPERTIES  _BACKTRACE_TRIPLES "/mnt/d/OneDrive - Office/File/Project/VS Code/C++/xianyi-OpenBLAS-efe4248/test/CMakeLists.txt;74;add_test;/mnt/d/OneDrive - Office/File/Project/VS Code/C++/xianyi-OpenBLAS-efe4248/test/CMakeLists.txt;0;")
add_test(sblas3 "sh" "/mnt/d/OneDrive - Office/File/Project/VS Code/C++/xianyi-OpenBLAS-efe4248/test/test_helper.sh" "/mnt/d/OneDrive - Office/File/Project/VS Code/C++/xianyi-OpenBLAS-efe4248/test/sblat3" "/mnt/d/OneDrive - Office/File/Project/VS Code/C++/xianyi-OpenBLAS-efe4248/test/sblat3.dat" "SBLAT3.SUMM")
set_tests_properties(sblas3 PROPERTIES  _BACKTRACE_TRIPLES "/mnt/d/OneDrive - Office/File/Project/VS Code/C++/xianyi-OpenBLAS-efe4248/test/CMakeLists.txt;76;add_test;/mnt/d/OneDrive - Office/File/Project/VS Code/C++/xianyi-OpenBLAS-efe4248/test/CMakeLists.txt;0;")
add_test(dblas1 "/mnt/d/OneDrive - Office/File/Project/VS Code/C++/xianyi-OpenBLAS-efe4248/test/dblat1")
set_tests_properties(dblas1 PROPERTIES  _BACKTRACE_TRIPLES "/mnt/d/OneDrive - Office/File/Project/VS Code/C++/xianyi-OpenBLAS-efe4248/test/CMakeLists.txt;72;add_test;/mnt/d/OneDrive - Office/File/Project/VS Code/C++/xianyi-OpenBLAS-efe4248/test/CMakeLists.txt;0;")
add_test(dblas2 "sh" "/mnt/d/OneDrive - Office/File/Project/VS Code/C++/xianyi-OpenBLAS-efe4248/test/test_helper.sh" "/mnt/d/OneDrive - Office/File/Project/VS Code/C++/xianyi-OpenBLAS-efe4248/test/dblat2" "/mnt/d/OneDrive - Office/File/Project/VS Code/C++/xianyi-OpenBLAS-efe4248/test/dblat2.dat" "DBLAT2.SUMM")
set_tests_properties(dblas2 PROPERTIES  _BACKTRACE_TRIPLES "/mnt/d/OneDrive - Office/File/Project/VS Code/C++/xianyi-OpenBLAS-efe4248/test/CMakeLists.txt;74;add_test;/mnt/d/OneDrive - Office/File/Project/VS Code/C++/xianyi-OpenBLAS-efe4248/test/CMakeLists.txt;0;")
add_test(dblas3 "sh" "/mnt/d/OneDrive - Office/File/Project/VS Code/C++/xianyi-OpenBLAS-efe4248/test/test_helper.sh" "/mnt/d/OneDrive - Office/File/Project/VS Code/C++/xianyi-OpenBLAS-efe4248/test/dblat3" "/mnt/d/OneDrive - Office/File/Project/VS Code/C++/xianyi-OpenBLAS-efe4248/test/dblat3.dat" "DBLAT3.SUMM")
set_tests_properties(dblas3 PROPERTIES  _BACKTRACE_TRIPLES "/mnt/d/OneDrive - Office/File/Project/VS Code/C++/xianyi-OpenBLAS-efe4248/test/CMakeLists.txt;76;add_test;/mnt/d/OneDrive - Office/File/Project/VS Code/C++/xianyi-OpenBLAS-efe4248/test/CMakeLists.txt;0;")
add_test(cblas1 "/mnt/d/OneDrive - Office/File/Project/VS Code/C++/xianyi-OpenBLAS-efe4248/test/cblat1")
set_tests_properties(cblas1 PROPERTIES  _BACKTRACE_TRIPLES "/mnt/d/OneDrive - Office/File/Project/VS Code/C++/xianyi-OpenBLAS-efe4248/test/CMakeLists.txt;72;add_test;/mnt/d/OneDrive - Office/File/Project/VS Code/C++/xianyi-OpenBLAS-efe4248/test/CMakeLists.txt;0;")
add_test(cblas2 "sh" "/mnt/d/OneDrive - Office/File/Project/VS Code/C++/xianyi-OpenBLAS-efe4248/test/test_helper.sh" "/mnt/d/OneDrive - Office/File/Project/VS Code/C++/xianyi-OpenBLAS-efe4248/test/cblat2" "/mnt/d/OneDrive - Office/File/Project/VS Code/C++/xianyi-OpenBLAS-efe4248/test/cblat2.dat" "CBLAT2.SUMM")
set_tests_properties(cblas2 PROPERTIES  _BACKTRACE_TRIPLES "/mnt/d/OneDrive - Office/File/Project/VS Code/C++/xianyi-OpenBLAS-efe4248/test/CMakeLists.txt;74;add_test;/mnt/d/OneDrive - Office/File/Project/VS Code/C++/xianyi-OpenBLAS-efe4248/test/CMakeLists.txt;0;")
add_test(cblas3 "sh" "/mnt/d/OneDrive - Office/File/Project/VS Code/C++/xianyi-OpenBLAS-efe4248/test/test_helper.sh" "/mnt/d/OneDrive - Office/File/Project/VS Code/C++/xianyi-OpenBLAS-efe4248/test/cblat3" "/mnt/d/OneDrive - Office/File/Project/VS Code/C++/xianyi-OpenBLAS-efe4248/test/cblat3.dat" "CBLAT3.SUMM")
set_tests_properties(cblas3 PROPERTIES  _BACKTRACE_TRIPLES "/mnt/d/OneDrive - Office/File/Project/VS Code/C++/xianyi-OpenBLAS-efe4248/test/CMakeLists.txt;76;add_test;/mnt/d/OneDrive - Office/File/Project/VS Code/C++/xianyi-OpenBLAS-efe4248/test/CMakeLists.txt;0;")
add_test(zblas1 "/mnt/d/OneDrive - Office/File/Project/VS Code/C++/xianyi-OpenBLAS-efe4248/test/zblat1")
set_tests_properties(zblas1 PROPERTIES  _BACKTRACE_TRIPLES "/mnt/d/OneDrive - Office/File/Project/VS Code/C++/xianyi-OpenBLAS-efe4248/test/CMakeLists.txt;72;add_test;/mnt/d/OneDrive - Office/File/Project/VS Code/C++/xianyi-OpenBLAS-efe4248/test/CMakeLists.txt;0;")
add_test(zblas2 "sh" "/mnt/d/OneDrive - Office/File/Project/VS Code/C++/xianyi-OpenBLAS-efe4248/test/test_helper.sh" "/mnt/d/OneDrive - Office/File/Project/VS Code/C++/xianyi-OpenBLAS-efe4248/test/zblat2" "/mnt/d/OneDrive - Office/File/Project/VS Code/C++/xianyi-OpenBLAS-efe4248/test/zblat2.dat" "ZBLAT2.SUMM")
set_tests_properties(zblas2 PROPERTIES  _BACKTRACE_TRIPLES "/mnt/d/OneDrive - Office/File/Project/VS Code/C++/xianyi-OpenBLAS-efe4248/test/CMakeLists.txt;74;add_test;/mnt/d/OneDrive - Office/File/Project/VS Code/C++/xianyi-OpenBLAS-efe4248/test/CMakeLists.txt;0;")
add_test(zblas3 "sh" "/mnt/d/OneDrive - Office/File/Project/VS Code/C++/xianyi-OpenBLAS-efe4248/test/test_helper.sh" "/mnt/d/OneDrive - Office/File/Project/VS Code/C++/xianyi-OpenBLAS-efe4248/test/zblat3" "/mnt/d/OneDrive - Office/File/Project/VS Code/C++/xianyi-OpenBLAS-efe4248/test/zblat3.dat" "ZBLAT3.SUMM")
set_tests_properties(zblas3 PROPERTIES  _BACKTRACE_TRIPLES "/mnt/d/OneDrive - Office/File/Project/VS Code/C++/xianyi-OpenBLAS-efe4248/test/CMakeLists.txt;76;add_test;/mnt/d/OneDrive - Office/File/Project/VS Code/C++/xianyi-OpenBLAS-efe4248/test/CMakeLists.txt;0;")
