# CMake generated Testfile for 
# Source directory: /mnt/d/OneDrive - Office/File/Project/VS Code/C++/xianyi-OpenBLAS-efe4248/ctest
# Build directory: /mnt/d/OneDrive - Office/File/Project/VS Code/C++/xianyi-OpenBLAS-efe4248/ctest
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(xscblat1 "/mnt/d/OneDrive - Office/File/Project/VS Code/C++/xianyi-OpenBLAS-efe4248/ctest/xscblat1")
set_tests_properties(xscblat1 PROPERTIES  _BACKTRACE_TRIPLES "/mnt/d/OneDrive - Office/File/Project/VS Code/C++/xianyi-OpenBLAS-efe4248/ctest/CMakeLists.txt;35;add_test;/mnt/d/OneDrive - Office/File/Project/VS Code/C++/xianyi-OpenBLAS-efe4248/ctest/CMakeLists.txt;0;")
add_test(xscblat2 "sh" "/mnt/d/OneDrive - Office/File/Project/VS Code/C++/xianyi-OpenBLAS-efe4248/ctest/test_cblas_helper.sh" "/mnt/d/OneDrive - Office/File/Project/VS Code/C++/xianyi-OpenBLAS-efe4248/ctest/xscblat2" "/mnt/d/OneDrive - Office/File/Project/VS Code/C++/xianyi-OpenBLAS-efe4248/ctest/sin2")
set_tests_properties(xscblat2 PROPERTIES  _BACKTRACE_TRIPLES "/mnt/d/OneDrive - Office/File/Project/VS Code/C++/xianyi-OpenBLAS-efe4248/ctest/CMakeLists.txt;47;add_test;/mnt/d/OneDrive - Office/File/Project/VS Code/C++/xianyi-OpenBLAS-efe4248/ctest/CMakeLists.txt;0;")
add_test(xscblat3 "sh" "/mnt/d/OneDrive - Office/File/Project/VS Code/C++/xianyi-OpenBLAS-efe4248/ctest/test_cblas_helper.sh" "/mnt/d/OneDrive - Office/File/Project/VS Code/C++/xianyi-OpenBLAS-efe4248/ctest/xscblat3" "/mnt/d/OneDrive - Office/File/Project/VS Code/C++/xianyi-OpenBLAS-efe4248/ctest/sin3")
set_tests_properties(xscblat3 PROPERTIES  _BACKTRACE_TRIPLES "/mnt/d/OneDrive - Office/File/Project/VS Code/C++/xianyi-OpenBLAS-efe4248/ctest/CMakeLists.txt;59;add_test;/mnt/d/OneDrive - Office/File/Project/VS Code/C++/xianyi-OpenBLAS-efe4248/ctest/CMakeLists.txt;0;")
add_test(xdcblat1 "/mnt/d/OneDrive - Office/File/Project/VS Code/C++/xianyi-OpenBLAS-efe4248/ctest/xdcblat1")
set_tests_properties(xdcblat1 PROPERTIES  _BACKTRACE_TRIPLES "/mnt/d/OneDrive - Office/File/Project/VS Code/C++/xianyi-OpenBLAS-efe4248/ctest/CMakeLists.txt;35;add_test;/mnt/d/OneDrive - Office/File/Project/VS Code/C++/xianyi-OpenBLAS-efe4248/ctest/CMakeLists.txt;0;")
add_test(xdcblat2 "sh" "/mnt/d/OneDrive - Office/File/Project/VS Code/C++/xianyi-OpenBLAS-efe4248/ctest/test_cblas_helper.sh" "/mnt/d/OneDrive - Office/File/Project/VS Code/C++/xianyi-OpenBLAS-efe4248/ctest/xdcblat2" "/mnt/d/OneDrive - Office/File/Project/VS Code/C++/xianyi-OpenBLAS-efe4248/ctest/din2")
set_tests_properties(xdcblat2 PROPERTIES  _BACKTRACE_TRIPLES "/mnt/d/OneDrive - Office/File/Project/VS Code/C++/xianyi-OpenBLAS-efe4248/ctest/CMakeLists.txt;47;add_test;/mnt/d/OneDrive - Office/File/Project/VS Code/C++/xianyi-OpenBLAS-efe4248/ctest/CMakeLists.txt;0;")
add_test(xdcblat3 "sh" "/mnt/d/OneDrive - Office/File/Project/VS Code/C++/xianyi-OpenBLAS-efe4248/ctest/test_cblas_helper.sh" "/mnt/d/OneDrive - Office/File/Project/VS Code/C++/xianyi-OpenBLAS-efe4248/ctest/xdcblat3" "/mnt/d/OneDrive - Office/File/Project/VS Code/C++/xianyi-OpenBLAS-efe4248/ctest/din3")
set_tests_properties(xdcblat3 PROPERTIES  _BACKTRACE_TRIPLES "/mnt/d/OneDrive - Office/File/Project/VS Code/C++/xianyi-OpenBLAS-efe4248/ctest/CMakeLists.txt;59;add_test;/mnt/d/OneDrive - Office/File/Project/VS Code/C++/xianyi-OpenBLAS-efe4248/ctest/CMakeLists.txt;0;")
add_test(xccblat1 "/mnt/d/OneDrive - Office/File/Project/VS Code/C++/xianyi-OpenBLAS-efe4248/ctest/xccblat1")
set_tests_properties(xccblat1 PROPERTIES  _BACKTRACE_TRIPLES "/mnt/d/OneDrive - Office/File/Project/VS Code/C++/xianyi-OpenBLAS-efe4248/ctest/CMakeLists.txt;35;add_test;/mnt/d/OneDrive - Office/File/Project/VS Code/C++/xianyi-OpenBLAS-efe4248/ctest/CMakeLists.txt;0;")
add_test(xccblat2 "sh" "/mnt/d/OneDrive - Office/File/Project/VS Code/C++/xianyi-OpenBLAS-efe4248/ctest/test_cblas_helper.sh" "/mnt/d/OneDrive - Office/File/Project/VS Code/C++/xianyi-OpenBLAS-efe4248/ctest/xccblat2" "/mnt/d/OneDrive - Office/File/Project/VS Code/C++/xianyi-OpenBLAS-efe4248/ctest/cin2")
set_tests_properties(xccblat2 PROPERTIES  _BACKTRACE_TRIPLES "/mnt/d/OneDrive - Office/File/Project/VS Code/C++/xianyi-OpenBLAS-efe4248/ctest/CMakeLists.txt;47;add_test;/mnt/d/OneDrive - Office/File/Project/VS Code/C++/xianyi-OpenBLAS-efe4248/ctest/CMakeLists.txt;0;")
add_test(xccblat3 "sh" "/mnt/d/OneDrive - Office/File/Project/VS Code/C++/xianyi-OpenBLAS-efe4248/ctest/test_cblas_helper.sh" "/mnt/d/OneDrive - Office/File/Project/VS Code/C++/xianyi-OpenBLAS-efe4248/ctest/xccblat3" "/mnt/d/OneDrive - Office/File/Project/VS Code/C++/xianyi-OpenBLAS-efe4248/ctest/cin3")
set_tests_properties(xccblat3 PROPERTIES  _BACKTRACE_TRIPLES "/mnt/d/OneDrive - Office/File/Project/VS Code/C++/xianyi-OpenBLAS-efe4248/ctest/CMakeLists.txt;59;add_test;/mnt/d/OneDrive - Office/File/Project/VS Code/C++/xianyi-OpenBLAS-efe4248/ctest/CMakeLists.txt;0;")
add_test(xzcblat1 "/mnt/d/OneDrive - Office/File/Project/VS Code/C++/xianyi-OpenBLAS-efe4248/ctest/xzcblat1")
set_tests_properties(xzcblat1 PROPERTIES  _BACKTRACE_TRIPLES "/mnt/d/OneDrive - Office/File/Project/VS Code/C++/xianyi-OpenBLAS-efe4248/ctest/CMakeLists.txt;35;add_test;/mnt/d/OneDrive - Office/File/Project/VS Code/C++/xianyi-OpenBLAS-efe4248/ctest/CMakeLists.txt;0;")
add_test(xzcblat2 "sh" "/mnt/d/OneDrive - Office/File/Project/VS Code/C++/xianyi-OpenBLAS-efe4248/ctest/test_cblas_helper.sh" "/mnt/d/OneDrive - Office/File/Project/VS Code/C++/xianyi-OpenBLAS-efe4248/ctest/xzcblat2" "/mnt/d/OneDrive - Office/File/Project/VS Code/C++/xianyi-OpenBLAS-efe4248/ctest/zin2")
set_tests_properties(xzcblat2 PROPERTIES  _BACKTRACE_TRIPLES "/mnt/d/OneDrive - Office/File/Project/VS Code/C++/xianyi-OpenBLAS-efe4248/ctest/CMakeLists.txt;47;add_test;/mnt/d/OneDrive - Office/File/Project/VS Code/C++/xianyi-OpenBLAS-efe4248/ctest/CMakeLists.txt;0;")
add_test(xzcblat3 "sh" "/mnt/d/OneDrive - Office/File/Project/VS Code/C++/xianyi-OpenBLAS-efe4248/ctest/test_cblas_helper.sh" "/mnt/d/OneDrive - Office/File/Project/VS Code/C++/xianyi-OpenBLAS-efe4248/ctest/xzcblat3" "/mnt/d/OneDrive - Office/File/Project/VS Code/C++/xianyi-OpenBLAS-efe4248/ctest/zin3")
set_tests_properties(xzcblat3 PROPERTIES  _BACKTRACE_TRIPLES "/mnt/d/OneDrive - Office/File/Project/VS Code/C++/xianyi-OpenBLAS-efe4248/ctest/CMakeLists.txt;59;add_test;/mnt/d/OneDrive - Office/File/Project/VS Code/C++/xianyi-OpenBLAS-efe4248/ctest/CMakeLists.txt;0;")
